name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-and-test-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [22, 24, 26]
        serialize-javascript: [6, 7]
    outputs:
      urls: ${{ steps.pkgprnew.outputs.urls }}
    steps:
      # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

        # v2
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          runtime: node@${{ matrix.node }}
          version: 11

      - run: pnpm ci

      - run: pnpm add serialize-javascript@${{ matrix.serialize-javascript }}
      - run: pnpm exec prettier --write ./pnpm-lock.yaml

      - name: Turborepo Remote Cache using Github Artifacts
        # v2.5.1
        uses: rharkor/caching-for-turbo@2238fae6eb9a9936f92356f54cb3660200d105e7
        with:
          # Scopes the local cache server key uniquely across OS, Node versions and other matrix inputs.
          cache-prefix: 'turbo-${{ matrix.os }}-node-${{ matrix.node }}-serialize-js-${{matrix.serialize-javascript}}'

      # Run checks and builds.
      - run: pnpm run check
        env:
          # Required environment variable to sign/verify remote cache artifacts
          TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      # Publish to pkgprnew to test publishing before actual publish.
      - name: Upload to pkgprnew. To test published package.
        id: pkgprnew
        if: matrix.node == 24 && matrix.serialize-javascript == 7
        run: pnpm dlx pkg-pr-new publish

  # Run tests against published package.
  test-published-package:
    runs-on: ubuntu-latest
    needs: check-and-test-publish
    steps:
      - run: 'echo ${{ needs.check-and-test-publish.outputs.urls }}'

      # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          runtime: node@24
          version: 11

      # Install only dev dependencies. Because the published package itself will have direct dependencies attached with it.
      - run: pnpm install --frozen-lockfile --dev

      - name: Install the published package for testing
        run: pnpm add pkgprnew-published@${{ needs.check-and-test-publish.outputs.urls }}

      - name: Turborepo Remote Cache using Github Artifacts
        # v2.5.1
        uses: rharkor/caching-for-turbo@2238fae6eb9a9936f92356f54cb3660200d105e7
        with:
          # Scopes the local cache server key uniquely across OS, Node versions and other matrix inputs.
          cache-prefix: 'turbo-ubuntu-latest-node-24-serialize-js-7'

      - name: Run tests against the published package
        run: pnpm exec turbo test
        env:
          TEST_PUBLISHED_PKG: 'true'
